<a href="https://colab.research.google.com/github/Saiakashaya/DATA_SCIENCE/blob/main/zscore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [3]:
!kaggle datasets download rtatman/digidb

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/rtatman/digidb
License(s): CC-BY-NC-SA-4.0
Downloading digidb.zip to /content
100% 14.3k/14.3k [00:00<00:00, 27.2MB/s]

In [4]:
ls-ltr /content

total 20
-rw-r--r-- 1 root root 14671 Sep 20  2019 digidb.zip
drwxr-xr-x 1 root root  4096 Jun  4 13:32 sample_data/

In [5]:
!unzip digidb.zip

Archive:  digidb.zip
  inflating: DigiDB_digimonlist.csv
  inflating: DigiDB_movelist.csv
  inflating: DigiDB_supportlist.csv

In [6]:
!chmod 777 DigiDB_supportlist.csv

In [7]:
import pandas as pd
df = pd.read_csv("DigiDB_supportlist.csv")
df.head()

               Name                                        Description
0     Adroit Wisdom                              Increases INT by 15%.
1       All-Rounder             Increases ATK, DEF, INT and SPD by 5%.
2           Analyze                      Increases scan values by 10%.
3  Animal Colosseum         Increases damage from Earth skills by 15%.
4      Aus Generics  Increases SPD and EVA by 25% when HP drops bel...

In [8]:
from scipy.stats import zscore
import numpy as np
data=pd.read_csv("DigiDB_supportlist.csv")
data.head()

               Name                                        Description
0     Adroit Wisdom                              Increases INT by 15%.
1       All-Rounder             Increases ATK, DEF, INT and SPD by 5%.
2           Analyze                      Increases scan values by 10%.
3  Animal Colosseum         Increases damage from Earth skills by 15%.
4      Aus Generics  Increases SPD and EVA by 25% when HP drops bel...

In [10]:
data['description_length'] = data['Description'].apply(len)
score = zscore(data['description_length'])
score

array([-1.34045437, -0.40813073, -0.90171383, -0.18876046,  0.41450777,
        1.51135911, -0.02423276,  1.78557195, -1.34045437, -0.07907533,
       -0.90171383,  0.46935034, -0.90171383, -0.18876046,  0.41450777,
       -0.2984456 ,  0.46935034, -0.90171383, -0.24360303, -1.34045437,
        1.12746114,  0.96293344, -0.24360303, -1.39529694, -1.34045437,
       -0.02423276, -0.90171383, -1.6146672 ,  0.30482264, -1.66950977,
        1.73072938,  1.45651655,  0.90809088,  1.34683141, -1.34045437,
       -0.24360303, -1.55982464,  1.18230371, -0.4629733 ,  0.90809088,
       -1.50498207, -0.51781586, -1.34045437, -0.7920287 , -0.18876046,
        1.01777601, -0.07907533,  1.62104425,  1.73072938, -0.68234357,
       -0.02423276, -0.02423276, -0.7920287 ,  0.35966521,  1.51135911,
        0.35966521, -0.2984456 ,  0.14029494,  0.30482264, -0.18876046,
       -0.24360303, -1.4501395 ,  1.18230371, -0.68234357,  2.22431248,
       -1.23076923, -0.7920287 ,  0.0306098 ,  0.19513751, -0.07907533,
        0.08545237, -0.627501  ,  1.29198884,  1.84041451,  0.0306098 ,
       -0.4629733 , -1.4501395 , -0.1339179 ,  2.49852532, -0.40813073,
       -0.07907533,  0.74356317,  1.51135911, -0.24360303,  0.24998007,
        0.24998007])